#配置文件
#如果您以前使用bc版本, 可以将此配置文件删除
#将原始的config.yml放入文件夹中, 插件将自动转换为.toml文件

#日志数量
#将会记录这个数量的聊天记录
log-num = 50

#延时毫秒数
#在玩家进入服务器后延时此时长后显示聊天记录
delay = 50

#文字输出格式
#将会按照此格式输出给玩家
#参照java的String.format()
# 1:服务器名称 2:玩家名 3:聊天内容 4:时间字符串 5:时间
#支持列表/字符串
#https://www.cnblogs.com/Dhouse/p/7776780.html 请参考此类文章
line-text = "§7> [%1$s]%2$s§7: %3$s"

#悬浮显示文字
#支持列表/字符串
hover-text = ["§6时间: %4$s"]
 
#日期格式
date-format = "yyyy-MM-dd HH:mm:ss"

#显示消息记录前显示的文字
prefix = "§7> 为你显示 %s 条聊天记录"
#显示消息记录后显示的文字
suffix = "§7> 以上是 %s 条聊天记录"


#消息过滤器
#符合条件的消息将不记录
[msgFilter]
#前缀匹配 - 消息中以下列开头的将不会被记录 
prefix  = ["/"]
#后缀匹配 - 消息中以下列结尾的将不会被记录
suffix  = []
#包含匹配 - 消息中包含下列字符串的将不会被记录
contain = []
#全字匹配 - 消息等于下列字符串的将不会被记录
equals  = []


#玩家过滤器
#符合条件的玩家将不记录
[playerFilter]
#全字匹配 - 玩家名在此列出的将不会被记录
name    = []
#包含匹配 - 玩家名包含下列字符串的将不会被记录
contain = []


#服务器过滤器
#符合条件的服务器将不记录
[serverFilter]
#全字匹配 - 服务器名在此列出的将不会被记录
name    = []
#包含匹配 - 服务器名包含下列字符串的将不会被记录
contain = []


#不显示的玩家
#符合条件的玩家将不会被展示聊天记录
[not-show-playerFilter]
name    = []
contain = []


#不显示的服务器
#当玩家登录于符合条件的服务器将不会被展示聊天记录
[not-show-serverFilter]
name    = []
contain = []


