name: Build yuanluChatLog

on:
  push:
    branches: [ Velocity ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build yuanluChatLog
        run: ./gradlew build

      - name: Release yuanluChatLog
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "yuanluChatLog v1.1.5"
          automatic_release_tag: "build-velocity"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "build/libs/yuanluchatlog-velocity-*.jar"
          prerelease: false
